version: '1.0'
networks:
  project:
    driver: bridge

services:
  api:
    container_name: api
    env_file:
      - .env.api
    build:
      dockerfile: ./api/dockerfile
    expose:
      - "3000"
    networks:
      - project
    restart: "on-failure"

  web:
    container_name: web
    env_file:
      - .env.web
    build:
      dockerfile: ./web/dockerfile
    ports:
      - "5000:80"
    networks:
      - project
    restart: "on-failure"
