### STAGE 1: Build ###
FROM node:16.20.0 as build-stage 
WORKDIR /app
COPY ./web/package*.json /app/
RUN yarn install
COPY ./web/ /app/
COPY .env.web /app/.env
RUN yarn run build

### STAGE 2: Run ###
FROM nginx:1.23.2
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist/ /var/www/default
